#import <Foundation/Foundation.h>
#import "SWGPriceEstimate.h"
#import "SWGError.h"
#import "SWGUUID.h"
#import "SWGProduct.h"
#import "SWGApi.h"

/**
* Uber API
* Move your app forward with the Uber API
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGEstimatesApi: NSObject <SWGApi>

extern NSString* kSWGEstimatesApiErrorDomain;
extern NSInteger kSWGEstimatesApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Price Estimates
/// The Price Estimates endpoint returns an estimated price range for each product offered at a given location. The price estimate is provided as a formatted string with the full price range and the localized currency symbol.<br><br>The response also includes low and high estimates, and the [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code for situations requiring currency conversion. When surge is active for a particular product, its surge_multiplier will be greater than 1, but the price estimate already factors in this multiplier. 
///
/// @param startLatitude Latitude component of start location.
/// @param startLongitude Longitude component of start location.
/// @param endLatitude Latitude component of end location.
/// @param endLongitude Longitude component of end location.
/// 
///  code:200 message:"An array of price estimates by product",
///  code:0 message:"Unexpected error"
///
/// @return NSArray<SWGPriceEstimate>*
-(NSNumber*) estimatesPriceGetWithStartLatitude: (NSNumber*) startLatitude
    startLongitude: (NSNumber*) startLongitude
    endLatitude: (NSNumber*) endLatitude
    endLongitude: (NSNumber*) endLongitude
    completionHandler: (void (^)(NSArray<SWGPriceEstimate>* output, NSError* error)) handler;


/// Time Estimates
/// The Time Estimates endpoint returns ETAs for all products offered at a given location, with the responses expressed as integers in seconds. We recommend that this endpoint be called every minute to provide the most accurate, up-to-date ETAs.
///
/// @param startLatitude Latitude component of start location.
/// @param startLongitude Longitude component of start location.
/// @param customerUuid Unique customer identifier to be used for experience customization. (optional)
/// @param productId Unique identifier representing a specific product for a given latitude &amp; longitude. (optional)
/// 
///  code:200 message:"An array of products",
///  code:0 message:"Unexpected error"
///
/// @return NSArray<SWGProduct>*
-(NSNumber*) estimatesTimeGetWithStartLatitude: (NSNumber*) startLatitude
    startLongitude: (NSNumber*) startLongitude
    customerUuid: (SWGUUID*) customerUuid
    productId: (NSString*) productId
    completionHandler: (void (^)(NSArray<SWGProduct>* output, NSError* error)) handler;



@end
