#import <Foundation/Foundation.h>
#import "SWGProduct.h"
#import "SWGError.h"
#import "SWGApi.h"

/**
* Uber API
* Move your app forward with the Uber API
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGProductsApi: NSObject <SWGApi>

extern NSString* kSWGProductsApiErrorDomain;
extern NSInteger kSWGProductsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Product Types
/// The Products endpoint returns information about the *Uber* products offered at a given location. The response includes the display name and other details about each product, and lists the products in the proper display order. 
///
/// @param latitude Latitude component of location.
/// @param longitude Longitude component of location.
/// 
///  code:200 message:"An array of products",
///  code:0 message:"Unexpected error"
///
/// @return NSArray<SWGProduct>*
-(NSNumber*) productsGetWithLatitude: (NSNumber*) latitude
    longitude: (NSNumber*) longitude
    completionHandler: (void (^)(NSArray<SWGProduct>* output, NSError* error)) handler;



@end
