#import <Foundation/Foundation.h>
#import "SWGActivities.h"
#import "SWGError.h"
#import "SWGProfile.h"
#import "SWGApi.h"

/**
* Uber API
* Move your app forward with the Uber API
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGUserApi: NSObject <SWGApi>

extern NSString* kSWGUserApiErrorDomain;
extern NSInteger kSWGUserApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// User Activity
/// The User Activity endpoint returns data about a user's lifetime activity with Uber. The response will include pickup locations and times, dropoff locations and times, the distance of past requests, and information about which products were requested.<br><br>The history array in the response will have a maximum length based on the limit parameter. The response value count may exceed limit, therefore subsequent API requests may be necessary.
///
/// @param offset Offset the list of returned results by this amount. Default is zero. (optional)
/// @param limit Number of items to retrieve. Default is 5, maximum is 100. (optional)
/// 
///  code:200 message:"History information for the given user",
///  code:0 message:"Unexpected error"
///
/// @return SWGActivities*
-(NSNumber*) historyGetWithOffset: (NSNumber*) offset
    limit: (NSNumber*) limit
    completionHandler: (void (^)(SWGActivities* output, NSError* error)) handler;


/// User Profile
/// The User Profile endpoint returns information about the Uber user that has authorized with the application.
///
/// 
///  code:200 message:"Profile information for a user",
///  code:0 message:"Unexpected error"
///
/// @return SWGProfile*
-(NSNumber*) meGetWithCompletionHandler: 
    (void (^)(SWGProfile* output, NSError* error)) handler;



@end
