#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Uber API
* Move your app forward with the Uber API
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol SWGProduct
@end

@interface SWGProduct : SWGObject

/* Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles. [optional]
 */
@property(nonatomic) NSString* productId;
/* Description of product. [optional]
 */
@property(nonatomic) NSString* _description;
/* Display name of product. [optional]
 */
@property(nonatomic) NSString* displayName;
/* Capacity of product. For example, 4 people. [optional]
 */
@property(nonatomic) NSString* capacity;
/* Image URL representing the product. [optional]
 */
@property(nonatomic) NSString* image;

@end
