#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Uber API
* Move your app forward with the Uber API
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol SWGPriceEstimate
@end

@interface SWGPriceEstimate : SWGObject

/* Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles [optional]
 */
@property(nonatomic) NSString* productId;
/* [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code. [optional]
 */
@property(nonatomic) NSString* currencyCode;
/* Display name of product. [optional]
 */
@property(nonatomic) NSString* displayName;
/* Formatted string of estimate in local currency of the start location. Estimate could be a range, a single number (flat rate) or \"Metered\" for TAXI. [optional]
 */
@property(nonatomic) NSString* estimate;
/* Lower bound of the estimated price. [optional]
 */
@property(nonatomic) NSNumber* lowEstimate;
/* Upper bound of the estimated price. [optional]
 */
@property(nonatomic) NSNumber* highEstimate;
/* Expected surge multiplier. Surge is active if surge_multiplier is greater than 1. Price estimate already factors in the surge multiplier. [optional]
 */
@property(nonatomic) NSNumber* surgeMultiplier;

@end
